---
title: "Limma Differental Expression"
author: "Christopher Eeles"
date: "17/12/2019"
output: html_document
---

```{r setup, include=FALSE}
library(data.table)
library(limma)
library(Biobase)
library(tidyverse)
```

## Data Preparation

```{r load_data}
# Load the tSet of interest
t <- 'TGGATES_humanLDH.rda'
load(t)
tSet <- TGGATES_humanldh ## TODO:: Replace this with function that can find loaded tSet

## Correct annotation issues
featureInfo(tSet, "rna")$gene_id <- gsub("_at_at$", "_at", featureInfo(tSet, "rna")$gene_id)
rownames(tSet@molecularProfiles$rna) <- gsub("_at_at$", "_at", rownames(molecularProfiles(tSet, "rna"))) # Remove all values after _ character
```

```{r subsetting}
  # Get the eSet from the tSet
  eset <- tSet@molecularProfiles$rna
  #eset <- eset[ , duration == '24']
  
  # Get the targets
  targets <- pData(eset)[, c("samplename", "drugid", "dose_level", "duration")]
```
  
## Linear Model Design

```{r }
  # Create combined factors for design matrix
  drug <- factor(targets$drugid)
  dose <- factor(targets$dose_level, levels = c("Control", "Low", "Middle", "High"))
  #duration <- factor(targets$duration)

  # Create design matrix for experimental design
  if (names(tSet) == 'drugMatrix_rat') {
    drug <- relevel(drug, 'DMSO')
    design <- model.matrix(~0+drug:dose)
    coefs <- paste0('drug', unique(drug[-1]))
  } else {
    design <- model.matrix(~0+drug+drug:dose)
  }
```

## Model Fitting and Statistical Analysis

```{r}
  # Fit a linear model based on design matrix
  fit <- lmFit(eset, design)
  
  # Predict coefficients using empirical Bayes moderation of SE
  # Generate a t-stat, moderated F-stat and log-odds of differential expression
  stats <- eBayes(fit)
```

```{r get_top_genes}
  # Look at results per drug
  drug <- 'Clozapine'
  results <- topTable(stats, coef = paste0('drug', drug, ':duration24:doseHigh'), n = nrow(exprs(eset)))
  head(results)
```

## Validating Results
 
```{r validating_log2fc}
tName <- 'RRM2-215'
featureData <- fData(eset)
phenoData <- pData(eset)
expression <- exprs(eset)

gene_id <- featureData[which(featureData$transcript_name == tName),]$gene_id
sample_ids <- phenoData[which(phenoData$drugid == drug),]$samplename
expression[gene_id, sample_ids]
```
  
```{r pca}
eset_ctrl <- eset[, eset$dose_level == "Control"]
pca <- prcomp(t(exprs(eset_ctrl)))
```

```{r}
colors <- pData(eset_ctrl)$exp_id
colors <- pData(eset_ctrl)$group_id
colors <- pData(eset_ctrl)$batchid
```


## Including Plots

```{r }
volcanoplot(stats, paste0('drug', drug, ':doseHigh'))
```
